@startuml ERD

object Customer {
  -id: ObjectID <<generated>>
  --
  *username: string
  *password: string
  *name: string
  *address: string
  *email: string
  *phoneNumber: string
  *gender: string
  *status: "active" | "inactive"
  *createdAt: date
  *updatedAt: date
}

object CartDetail {
  ~customerId: string
  ~productId: string
  ~amount: number
  --
  *createdAt: date
  *updatedAt: date
}

object Agency {
  -id: ObjectID <<generated>>
  --
  *username: string
  *password: string
  *name: string
  *address: string
  *email: string
  *phoneNumber: string
  *gender: string
  *status: "active" | "inactive"
  *isDeleted: boolean
  *createdAt: date
  *updatedAt: date
}

object Product {
  -id: ObjectId <<generated>>
  --
  ~agencyId: string
  --
  *productName: string
  *price: number
  *amount: number
  *category: string
  *createdAt: date
  *updatedAt: date
}

object Billing{
  -id: ObjectId <<generated>>
  --
  ~agencyId: string
  ~customerId: string
  --
  *status: "ordered" | "being shipped" | "complete" | "return" | "refund"
  *totalAmount: number
  *totalCost: number
  *createdAt: date
}
object BillingDetail {
  ~customerId: string
  ~productId: string
  --
  *amount: number
  *createdAt: date
}
object Transaction {
  -id: ObjectId <<generated>>
  --
  ~billingId: string
  --
  *amount: number
  *type: "checkout" | "refund"
  *createdAt: date
}


object Admin {
  -id: ObjectId <<generated>>
  --
  *username: string
  *password: string
}


Agency ||-right-o{ Billing
Agency ||-up-o{ Product
Billing }o-right-|| Customer

Product ||-right-o{ CartDetail
CartDetail }o-down-|| Customer

Product ||-down-o{ BillingDetail

Billing ||-up-o{ BillingDetail
Billing ||-down-o{ Transaction


@enduml
