
@startuml

left to right direction

(manage agency) ..> (read agency information): <<include>>
(manage agency) ..> (create agency): <<include>>
(manage agency) ..> (update agency): <<include>>
(manage agency) ..> (delete agency): <<include>>


Admin --> (manage agency)

(manage owned product) ..> (read owned product information): <<include>>
(manage owned product) ..> (create owned product): <<include>>
(manage owned product) ..> (update owned product): <<include>>
(manage owned product) ..> (delete owned product): <<include>>

Agency --> (manage owned product)
Agency --> (read transactions, billing of owned product)

User --> (login)
User --> (logout)
User --> (read product's transactions, billings)
User --> (read agency information)
@enduml
